/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:56cc65f3-c501-40b6-a396-8834aabd1efa",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_n67Aa6jmT",
    "aws_user_pools_web_client_id": "1nmoqceoiijpn9v86o2j08k85o",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_dynamodb_all_tables_region": "eu-north-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "restaurants-dev",
            "region": "eu-north-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://l36lckp33jgardxv57qh4wprry.appsync-api.eu-north-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-north-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-l6lwthapbzfovefibvjmw62qra"
};


export default awsmobile;
